### ISSUE TITLE
3.10.0: FTBFS: 'iota' is not a member of 'std'

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#402]
3.9.4 currently FTBFS in Debian _sid_:

~~~~
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_InsertTest_Test::TestBody()': 
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc:58:2: error: 'iota' is not a member of 'std' 
  std::iota(range.begin(), range.end(), 1); 
  ^ 
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_EraseTest_Test::TestBody()': 
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc:80:2: error: 'iota' is not a member of 'std' 
  std::iota(range.begin(), range.end(), 1); 
  ^ 
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_IteratorTest_Test::TestBody()': 
/build/lizardfs-3.9.4+dfsg/src/common/compact_vector_unittest.cc:107:2: error: 'iota' is not a member of 'std' 
  std::iota(vec.begin(), vec.end(), 0); 
  ^ 
src/common/CMakeFiles/mfscommon_tests.dir/build.make:137: recipe for target 'src/common/CMakeFiles/mfscommon_tests.dir/compact_vector_unittest.cc.o' failed 
~~~~

Please advise.

**Comment by Fretek** [comment]
Include file "numeric" is missing.
This was fixed in commit eff7619

**Comment by onlyjob** [comment]
Unfortunately I'm unable to confirm whether it fixes the problem as compilation fails with another problem reported in #403...

**Comment by Fretek** [comment]
Is this still the issue?

**Comment by onlyjob** [comment]
All good, thank you.

**Comment by onlyjob** [comment]
3.10.0 FTBFS again:

~~~~
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_InsertTest_Test::TestBody()': 
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc:58:2: error: 'iota' is not a member of 'std' 
  std::iota(range.begin(), range.end(), 1); 
  ^~~ 
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_EraseTest_Test::TestBody()': 
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc:80:2: error: 'iota' is not a member of 'std' 
  std::iota(range.begin(), range.end(), 1); 
  ^~~ 
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc: In member function 'virtual void CompactVectorTest_IteratorTest_Test::TestBody()': 
/build/lizardfs-3.10.0+dfsg/src/common/compact_vector_unittest.cc:107:2: error: 'iota' is not a member of 'std' 
  std::iota(vec.begin(), vec.end(), 0); 
  ^~~ 
~~~~

Why do we have to go through this more than once??

**Comment by onlyjob** [comment]
Fixed in 3.10.2. Thanks.
