### ISSUE TITLE
Nfs-Ganesha plugin

### ISSUE THREAD

**Issue by alexinc2000** [lizardfs/lizardfs#878]
LisardFS 1.13.0-rc2
Plugin for nfs-ganesha
Debian 10 (is up)
Nfs-ganesha 2.7.1
Get error: 
Error: /usr/lib/x86_64-linux-gnu/ganesha/libfsallizardfs.so: undefined symbol:: fsale_lease_time,
How can i start ganesha?

**Comment by tanertas** [comment]
Outout of the command below may helpful:
`ldd /usr/lib/x86_64-linux-gnu/ganesha/libfsallizardfs.so`

**Comment by alexinc2000** [comment]
ldd /usr/lib/x86_64-linux-gnu/ganesha/libfsallizardfs.so
        linux-vdso.so.1 (0x00007ffd56329000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1b088ff000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1b088f5000)
        libisal.so.2 => /lib/x86_64-linux-gnu/libisal.so.2 (0x00007f1b088b6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1b088b1000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1b0872d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1b085aa000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1b0858e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1b0856d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1b083ac000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1b08b83000)

**Comment by alexinc2000** [comment]
I checked all libs - it presents in my systems. Maybe nfs-ganesha packedge should another version?

**Comment by alexinc2000** [comment]
Install Ganesha 3.2 - take other mistake:  undefined symbol:: fsal_maxpathlen

**Comment by alexinc2000** [comment]
Now, after trying to compile source code, i understand that it plugin use ganesha 2.5. But i coudn't to install it on Debian Buster - it's so old. Is any idea?

**Comment by alexinc2000** [comment]
Try to compile with ganesha 2.7 stable. Get this mistake:
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c: In function ‘lzfs_fsal_fs_lease_time’:
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c:331:9: warning: implicit declaration of function ‘fsal_lease_time’; did you mean ‘fsal_release_attrs’? [-Wimplicit-function-declaration]
  return fsal_lease_time(info);
         ^~~~~~~~~~~~~~~
         fsal_release_attrs
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c:331:9: error: incompatible types when returning type ‘int’ but ‘struct timespec’ was expected
  return fsal_lease_time(info);
         ^~~~~~~~~~~~~~~~~~~~~
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c: In function ‘lzfs_fsal_fs_xattr_access_rights’:
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c:379:9: warning: implicit declaration of function ‘fsal_xattr_access_rights’; did you mean ‘lzfs_fsal_fs_xattr_access_rights’? [-Wimplicit-function-declaration]
  return fsal_xattr_access_rights(info);
         ^~~~~~~~~~~~~~~~~~~~~~~~
         lzfs_fsal_fs_xattr_access_rights
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c: In function ‘lzfs_fsal_export_ops_init’:
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c:414:5: error: ‘struct export_ops’ has no member named ‘fs_lease_time’
  ops->fs_lease_time = lzfs_fsal_fs_lease_time;
     ^~
/root/lizardfs-3.13.0-rc2/src/nfs-ganesha/export.c:418:5: error: ‘struct export_ops’ has no member named ‘fs_xattr_access_rights’
  ops->fs_xattr_access_rights = lzfs_fsal_fs_xattr_access_rights;
And i don't now - what do on next step. I don't know C++ and C :(

**Comment by zserik** [comment]
It would be probably a good idea for the `lizardfs´ project to bump the `nfs-ganesha` and `ntirpc` versions, as both seem to be rather outdated and aren't present in some distro repos anymore...

**Comment by ffilz** [comment]
nfs-ganesha maintainer here - yes. it would be good to move to nfs-ganesha V3.5, or preferably even V4.0 as we will not be supporting V3.5
